### ISSUE TITLE
Json Format Hatası

### ISSUE THREAD

**Issue by desstannoz** [tarikguney/OAuth20#1]
Merhaba hocam;
`var headerBytes = Encoding.UTF8.GetBytes($"{{'alg':'{HmacAlgorithm.HSA256}', 'typ': 'JWT'}}");
  var headerBase = Base64UrlEncoder.Encode(headerBytes);`

Kodunda Json formatı yanlış olarak alınıyor.
### **### Çözüm Kodu:**

`var headerJson = JsonConvert.DeserializeObject($"{{'alg':'{HmacAlgorithm.HS256}', 'typ': 'JWT'}}").ToString();

var headerBytes = Encoding.UTF8.GetBytes(headerJson);
var headerBase = Base64UrlEncoder.Encode(headerBytes);`

Bu şekilde Json çıktısı: 
> {
  "alg": "HS256",
  "typ": "JWT"
}

**haderBase çıktısınıı jwt.io dan decode yaptırdığımızda Header çıktısını görebiliyoruz.**

**Comment by desstannoz** [comment]
```
var headerJson = JsonConvert.DeserializeObject($"{{'alg':'{HmacAlgorithm.HS256}', 'typ': 'JWT'}}").ToString();
            var headerBytes = Encoding.UTF8.GetBytes(headerJson);
            var headerBase = Base64UrlEncoder.Encode(headerBytes);

            var payloadBytes =
                Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(new JwtToken() { Name = "Kazim Ozkurt" }));
            var payloadBase = Base64UrlEncoder.Encode(payloadBytes);

            var payload = headerBase + "." + payloadBase;
``` 
@tarikguney

**Comment by tarikguney** [comment]
@desstannoz Supersin! Sana zahmet PR gonderebilir misin?

**Comment by desstannoz** [comment]
> @desstannoz Supersin! Sana zahmet PR gonderebilir misin?

Tabi hocam son yaptıklarınızı da pushlar mısınız acaba?

**Comment by desstannoz** [comment]
#3 Fixed
